### ISSUE TITLE
获取答案出错

### ISSUE THREAD

**Issue by Yonnemy2nd** [ayanamiblhx/nonebot_plugin_youthstudy#1]
上周无问题。
错误信息：string index out of range

**Comment by ayanamiblhx** [comment]
> 上周无问题。
> 错误信息：string index out of range

估计又出了啥bug，等会我看看

**Comment by ayanamiblhx** [comment]
> 上周无问题。 错误信息：string index out of range

原因是本次青年大学习加了个课件小问卷，不属于答题的范畴，直接把获取答案的规则给搞崩了

**Comment by Yonnemy2nd** [comment]
草，那这还蛮尬尴的
