### ISSUE TITLE
运行bot之后data文件夹中没有产生study_config

### ISSUE THREAD

**Issue by Zhcs0712** [ayanamiblhx/nonebot_plugin_youthstudy#13]
确定机器人完全启动了，其它插件都可以正常运行
全局搜索也没找到study_config

**Comment by ayanamiblhx** [comment]
> 确定机器人完全启动了，其它插件都可以正常运行
> 全局搜索也没找到study_config

pip show nonebot_plugin_youthstudy查看版本

**Comment by Zhcs0712** [comment]
1.0.7

**Comment by ayanamiblhx** [comment]
> 1.0.7

python版本是不是3.9以下

**Comment by Zhcs0712** [comment]
3.8.10

**Comment by ayanamiblhx** [comment]
> 3.8.10

升级到3.9再更新就好了

**Comment by Zhcs0712** [comment]
OKOK
谢谢
