### ISSUE TITLE
获取答案出错

### ISSUE THREAD

**Issue by copurxia** [ayanamiblhx/nonebot_plugin_youthstudy#14]
出错了，错误信息：Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by ayanamiblhx** [comment]
> 出错了，错误信息：Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

使用`pip show nonebot_plugin_youthstudy`看看版本号

**Comment by copurxia** [comment]
Name: nonebot-plugin-youthstudy
Version: 1.1.2
Summary: 基于nonebot2的青年大学习插件
Home-page: https://github.com/ayanamiblhx/nonebot_plugin_youthstudy
Author: ayanamiblhx
Author-email: 1196818079@qq.com
License: GNU General Public License v3.0
Location: /home/ubuntu/.local/lib/python3.10/site-packages
Requires: beautifulsoup4, httpx, nonebot-adapter-onebot, nonebot-plugin-apscheduler, nonebot2, Pillow
Required-by:

**Comment by ayanamiblhx** [comment]
我这边能获取答案，你是什么场景下产生这样的报错?

**Comment by copurxia** [comment]
发送青年大学习口令时机器人的回复

**Comment by ayanamiblhx** [comment]
使用命令`pip install lxml`试试****

**Comment by copurxia** [comment]
万分感谢，已经ok了
