### ISSUE TITLE
出错了，错误信息：'Response' object has no attribute 'apparent_encoding'

### ISSUE THREAD

**Issue by copurxia** [ayanamiblhx/nonebot_plugin_youthstudy#15]
抱歉打扰了，他又报错了
这次是在回应截图口令（两个口令都返回这个）

**Comment by ayanamiblhx** [comment]
> 抱歉打扰了，他又报错了
> 这次是在回应截图口令（两个口令都返回这个）

应该是出bug了，明天看看

**Comment by copurxia** [comment]
万分感谢

**Comment by Z735803792** [comment]
+1，以下是nb端输出
```
09-08 09:33:40 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_youthstudy, type=message, priority=1, temp=False>
09-08 09:33:41 [ERROR] nonebot_plugin_youthstudy | 'Response' object has no attribute 'apparent_encoding'
09-08 09:33:41 [ERROR] nonebot_plugin_youthstudy | 2022-09-08 09:33:41.348799: 错误信息：'Response' object has no attribute 'apparent_encoding'
09-08 09:33:41 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_youthstudy, type=message, priority=1, temp=False> running complete
```

**Comment by ayanamiblhx** [comment]
> +1，以下是nb端输出
> ```
> 09-08 09:33:40 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_youthstudy, type=message, priority=1, temp=False>
> 09-08 09:33:41 [ERROR] nonebot_plugin_youthstudy | 'Response' object has no attribute 'apparent_encoding'
> 09-08 09:33:41 [ERROR] nonebot_plugin_youthstudy | 2022-09-08 09:33:41.348799: 错误信息：'Response' object has no attribute 'apparent_encoding'
> 09-08 09:33:41 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_youthstudy, type=message, priority=1, temp=False> running complete
> ```

已修复
