### ISSUE TITLE
版本依赖有问题，请更新，无法导入模块

### ISSUE THREAD

**Issue by BronzedOreo** [ayanamiblhx/nonebot_plugin_youthstudy#18]
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/71474660/208842748-9536310f-6ff4-439d-ad73-4104172ac870.png">

**Comment by ayanamiblhx** [comment]
> <img alt="image" width="1587" src="https://user-images.githubusercontent.com/71474660/208842748-9536310f-6ff4-439d-ad73-4104172ac870.png">

已修复
