### ISSUE TITLE
获取答案出错（尝试了之前所有issue的解决办法）

### ISSUE THREAD

**Issue by plumephoenix** [ayanamiblhx/nonebot_plugin_youthstudy#19]
出错了，错误信息同样是：Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
已安装lxml依赖
不过有一点不一样的是使用pip show nonebot_plugin_youthstudy看版本号，显示not found [nonebot_plugin_youthstudy]
目前大学习的截图，帮助等命令好用，只有请求答案（青年大学习/大学习）的时候报错

**Comment by ayanamiblhx** [comment]
> 出错了，错误信息同样是：Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library? 已安装lxml依赖 不过有一点不一样的是使用pip show nonebot_plugin_youthstudy看版本号，显示not found [nonebot_plugin_youthstudy] 目前大学习的截图，帮助等命令好用，只有请求答案（青年大学习/大学习）的时候报错

已修复
