### ISSUE TITLE
错误信息

### ISSUE THREAD

**Issue by ShiraYuki323** [ayanamiblhx/nonebot_plugin_youthstudy#2]
出错了，错误信息 'locale' codec can't encode character '\u6708' in position 2: encoding error
不知道啥问题.....

**Comment by ayanamiblhx** [comment]
> 出错了，错误信息 'locale' codec can't encode character '\u6708' in position 2: encoding error 不知道啥问题.....

更新试试

**Comment by ShiraYuki323** [comment]
用pip更新过了 还是这样。。

**Comment by ayanamiblhx** [comment]
> 用pip更新过了 还是这样。。

pip更新源较慢，你直接下载源文件覆盖

**Comment by ShiraYuki323** [comment]
ok 我试试

**Comment by ShiraYuki323** [comment]
下载源文件覆盖了还是这样...

**Comment by ayanamiblhx** [comment]
> 下载源文件覆盖了还是这样...

看一下错误截图，gocq和nb都要

**Comment by ShiraYuki323** [comment]
![P~$P)82O}`AR(XX7E6 CPHU](https://user-images.githubusercontent.com/76277519/146707619-86463e91-00f5-4168-b011-7a73e53c67e6.png)
![{OPB~3F WHRTKLJZ{0JA8_2](https://user-images.githubusercontent.com/76277519/146707627-be297664-9e66-48ab-8834-eb7c8e225456.png)

**Comment by ayanamiblhx** [comment]
> ![P~$P)82O}`AR(XX7E6 CPHU](https://user-images.githubusercontent.com/76277519/146707619-86463e91-00f5-4168-b011-7a73e53c67e6.png) ![{OPB~3F WHRTKLJZ{0JA8_2](https://user-images.githubusercontent.com/76277519/146707627-be297664-9e66-48ab-8834-eb7c8e225456.png)

试试这个：
import locale
locale.setlocale(locale.LC_CTYPE, 'chinese')

**Comment by ayanamiblhx** [comment]
> ![P~$P)82O}`AR(XX7E6 CPHU](https://user-images.githubusercontent.com/76277519/146707619-86463e91-00f5-4168-b011-7a73e53c67e6.png) ![{OPB~3F WHRTKLJZ{0JA8_2](https://user-images.githubusercontent.com/76277519/146707627-be297664-9e66-48ab-8834-eb7c8e225456.png)

源文件已更新，你再下载来试试

**Comment by ShiraYuki323** [comment]
我吧代码加上了 不报错了 谢谢大佬
