### ISSUE TITLE
建议删除内置插件名称

### ISSUE THREAD

**Issue by kexue-z** [ayanamiblhx/nonebot_plugin_youthstudy#3]
因为ddl说`__plugin_name__ `最好不要自己定义

[__plugin_name__ = "青年大学习"](https://github.com/ayanamiblhx/nonebot_plugin_youthstudy/blob/650a93b77105153b8a31f99b3506be225339c075/nonebot_plugin_youthstudy/__init__.py#L9)

**Comment by ayanamiblhx** [comment]
> 因为ddl说`__plugin_name__ `最好不要自己定义
> 
> [**plugin_name** = "青年大学习"](https://github.com/ayanamiblhx/nonebot_plugin_youthstudy/blob/650a93b77105153b8a31f99b3506be225339c075/nonebot_plugin_youthstudy/__init__.py#L9)

已删除

**Comment by kexue-z** [comment]
好耶
