### ISSUE TITLE
lxml报错

### ISSUE THREAD

**Issue by Harris-H** [ayanamiblhx/nonebot_plugin_youthstudy#4]
出错了，错误信息：Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

请问是lxml的版本问题吗？如何解决

**Comment by ayanamiblhx** [comment]
> 出错了，错误信息：Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
> 
> 
> 请问是lxml的版本问题吗？如何解决

哪个版本，更新了没

**Comment by Harris-H** [comment]
> 

噢，我的文件目录位置有点问题，现在好了，solved，thx。
