### ISSUE TITLE
最新一期的青年大学习没有答案

### ISSUE THREAD

**Issue by Copaan** [ayanamiblhx/nonebot_plugin_youthstudy#6]
运行起来只有Matcher <Matcher from plugins_kz.youthstudy, type=message, priority=5, temp=False> running complete一行

**Comment by ayanamiblhx** [comment]
> 运行起来只有Matcher <Matcher from plugins_kz.youthstudy, type=message, priority=5, temp=False> running complete一行

已更新

**Comment by Copaan** [comment]
谢佬，已解决
